### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by ishak52** [ishak52/AniFlix---Team-Lead-assignment#1]
**AS A USER I CAN:**
- [ ] make a new account on the platform.
- [ ] login/logout in the platform.
- [ ] view all videos exist in the platform.
- [ ] view any video when I click on it.
- [ ] search for any video I want according to its category filtered by(animal name, most viewed, most popular).
