### ISSUE TITLE
Video display page

### ISSUE THREAD

**Issue by ishak52** [ishak52/AniFlix---Team-Lead-assignment#10]
- [ ] Front End #6 (Video display page).
- [ ] Back End #5  (_user/home/video/:category-name/:video-id).
    - [ ] Videos display section #4  ( getVideoById).
- [ ] Test.
