### ISSUE TITLE
Platform Pages (React Components)

### ISSUE THREAD

**Issue by ishak52** [ishak52/AniFlix---Team-Lead-assignment#6]
- [ ] Login page.
- [ ] Home Page.
   - [ ] Header component.
   - [ ] Filter component.
   - [ ] Videos section component.
- [ ] Videos by animal name page.
- [ ] Video display page.
