### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ishak52** [ishak52/AniFlix---Team-Lead-assignment#7]
- [x] Front End #6 (Login Page).
- [ ] Back End #5  (_/login)
    - [ ] Authentication #4  (verifyUser, getUserData)
- [ ] Test.
