### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by ishak52** [ishak52/AniFlix---Team-Lead-assignment#8]
- [ ] Front End #6 (Home Page).
- [ ] Back End #5  (_user/home).
    - [ ] All Videos section #4  ( getAllVideos).
- [ ] Test.
