### ISSUE TITLE
Videos by animal name page

### ISSUE THREAD

**Issue by ishak52** [ishak52/AniFlix---Team-Lead-assignment#9]
- [ ] Front End #6 (Videos by animal name page).
- [ ] Back End #5  ( _user/home/video/:category-name.).
    - [ ] specific Animal Videos section #4  ( getVideosByName).
- [ ] Test.
